INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("302010200","Rua e estrada - superfície utilizada para sustentar pessoas");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("302010250","Calçada ou caminho para pedestre - superfície utilizada para sustentar pessoas");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("302010300","Piso de edifício - superfície utilizada para sustentar pessoas");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("302010350","Escada permanente cujos degraus permitem apoio integral do pé, degrau - superfície utilizada para sustentar pessoas");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("302010400","Rampa - superfície utilizada para sustentar pessoas");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("302010450","Passarela ou plataforma permanentes - superfície utilizada para sustentar pessoas");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("302010500","Piso de mina - superfície utilizada para sustentar pessoas");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("302010550","Chão - superfície utilizada para sustentar pessoas");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("302010600","Piso de andaime e plataforma desmontável - superfície utilizada para sustentar pessoas");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("302010650","Piso de veiculo - superfície utilizada para sustentar pessoas");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("302010700","Telhado");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("302010900","Superfície de sustentação, NIC - superfície utilizada para sustentar pessoas");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("302030900","Escada móvel ou fixada, NIC");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("302050100","Edifício - edifício ou estrutura");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("302050200","Depósito fixo (tanque, silo, paiol, etc.) - edifício ou estrutura");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("302050300","Cais, doca - edifício ou estrutura");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("302050400","Dique, barragem – edifício ou estrutura");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("302050500","Ponte, viaduto - edifício ou estrutura");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("302050600","Arquibancada, estádio - edifício ou estrutura");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("302050700","Andaime, plataforma - edifício ou estrutura");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("302050800","Torre, poste - edifício ou estrutura");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("302050900","Edifício ou estrutura (exceto piso, superfície de sustentação ou área de circulação), NIC");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("302070100","Escavação (para edifício, estrada, etc.)");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("302070300","Canal, fosso");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("302070500","Poço, entrada, galeria, etc., de mina");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("302070700","Túnel");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("302070900","Escavação, fosso, túnel, NIC");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("302090000","Superfície e estrutura, NIC");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303010040","Martelo, malho, marreta - ferramenta manual sem força motriz");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303010080","Machadinha, enxó - ferramenta manual sem força motriz");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303010120","Faca, facão - ferramenta manual sem força motriz");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303010160","Tesoura, tesourão - ferramenta manual sem força motriz");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303010200","Formão, cinzel - ferramenta manual sem força motriz");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303010240","Serra, serrote - ferramenta manual sem força motriz");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303010280","Alicate, torques, tenaz - ferramenta manual sem força motriz");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303010320","Plaina - ferramenta manual sem força motriz");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303010360","Lima, grosa - ferramenta manual sem força motriz");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303010400","Punção, ponteiro, vazador, talhadeira - ferramenta manual sem força motriz");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303010440","Pua, trado, verruma, máquina de furar manual - ferramenta manual sem força motriz");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303010480","Chave de parafuso - ferramenta manual sem força motriz");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303010520","chave de porca ou de abertura regulável, chave de boca - ferramenta manual sem força motriz");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303010560","Alavanca, pé-de-cabra - ferramenta manual sem força motriz");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303010600","Corda, cabo, corrente - ferramenta manual sem força motriz");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303010640","Machado - ferramenta manual sem força motriz");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303010680","Enxada, enxadão, sacho - ferramenta manual sem força motriz");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303010720","Pá, cavadeira - ferramenta manual sem força motriz");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303010760","Picareta - ferramenta manual sem força motriz");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303010800","Garfo, ancinho, forcado - ferramenta manual sem força motriz");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303010900","Ferramenta manual sem força motriz, NIC");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303015050","Martelete, socador - ferramenta portátil com força motriz ou aquecimento");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303015100","Talhadeira - ferramenta portátil com força motriz ou aquecimento");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303015150","Cortadeira, guilhotina - ferramenta portátil com força motriz ou aquecimento");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303015200","Serra - ferramenta portátil com força motriz ou aquecimento");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303015250","Punção, ponteiro, vazador - ferramenta portátil com força motriz ou aquecimento");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303015300","Perfuratriz - ferramenta portátil com força motriz ou aquecimento");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303015350","Rebitadeira - ferramenta portátil com força motriz ou aquecimento");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303015400","Máquina de aparafusar - ferramenta portátil com força motriz ou aquecimento");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303015450","Esmeril - ferramenta portátil com força motriz ou aquecimento");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303015500","Politriz, enceradeira - ferramenta portátil com força motriz ou aquecimento");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303015550","Ferro de passar - ferramenta portátil com força motriz ou aquecimento");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303015600","Ferramenta de soldagem - ferramenta portátil com força motriz ou aquecimento");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303015650","Maçarico - ferramenta portátil com força motriz ou aquecimento");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303015700","Ferramenta acionada por explosivo - ferramenta portátil com força motriz ou aquecimento");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303015750","Jato de areia - ferramenta portátil com força motriz ou aquecimento");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303015900","Ferramenta portátil com forca motriz ou aquecimento, NIC");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303020040","Serra - máquina");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303020080","Tesoura, guilhotina, máquina de cortar - máquina");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303020120","Laminadora, calandra - máquina");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303020160","Furadeira, broqueadeira, torno, freza - máquina");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303020200","Prensa - máquina");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303020240","Plaina, tupia - máquina");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303020280","Máquina de fundir, de forjar, de soldar");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303020320","Britador, moinho - máquina");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303020360","Misturador, batedeira, agitador - máquina");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303020400","Peneira mecânica, máquina separadora - máquina");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303020440","Politriz, lixadora, esmeril - máquina");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303020480","Máquina de terraplenagem e construção de estrada");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303020520","Máquina de mineração e perfuração (de túnel, poço, etc.)");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303020560","Máquina agrícola");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303020600","Máquina têxtil");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303020640","Máquina de costurar e de pespontar");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303020680","Máquina de imprimir");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303020720","Máquina de escritório");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303020760","Máquina de embalar ou empacotar");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303020900","Máquina, NIC");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303025300","Transportador por gravidade");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303025600","Transportador com força motriz");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303025900","Transportador, NIC");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303030050","Guindaste - equipamento de guindar");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303030100","Ponte rolante - equipamento de guindar");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303030150","Elevador - equipamento de guindar");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303030200","Elevador de caçamba para mineração - equipamento de guindar");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303030250","Pá mecânica, draga - equipamento de guindar");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303030300","Talha - equipamento de guindar");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303030350","Pau de carga - equipamento de guindar");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303030400","Macaco (mecânico, hidráulico, pneumático) - equipamento de guindar");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303030450","Guincho pneumático - equipamento de guindar");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303030500","Guincho elétrico - equipamento de guindar");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303030900","Equipamento de guindar, NIC");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303035300","Correia - dispositivo de transmissão de energia mecânica");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303035400","Corrente, corda, cabo - dispositivo de transmissão de energia mecânica");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303035500","Tambor, polia, roldana - dispositivo de transmissão de energia mecânica");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303035600","Embreagem de fricção - dispositivo de transmissão de energia mecânica");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303035700","Engrenagem - dispositivo de transmissão de energia mecânica");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303035900","Dispositivo de transmissão de energia mecânica, NIC");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303040100","Gerador - equipamento elétrico");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303040200","Condutor - equipamento elétrico");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303040300","Transformador, conversor - equipamento elétrico");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303040400","Painel de controle, barramento, chave, interruptor, disjuntor, fusível - equipamento elétrico");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303040500","Reostato, dispositivo de partida e aparelho de controle, capacitor, retificador, bateria de acumuladores - equipamento elétrico");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303040600","Motor elétrico - equipamento elétrico");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303040700","Equipamento magnético - equipamento elétrico");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303040750","Equipamento eletrolítico - equipamento elétrico");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303040800","Equipamento de aquecimento elétrico - equipamento elétrico");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303040900","Equipamento elétrico, NIC");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303045200","Motor (combustão interna, vapor)");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303045400","Bomba");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303045600","Turbina");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303045900","Motor, bomba, turbina, NIC");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303050200","Caldeira");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303050400","Vaso sob pressão (para líquido, gás ou vapor)");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303050600","Tubo sob pressão (mangueira ou tubo para liquido, gás ou vapor)");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303050900","Caldeira, vaso sob pressão, NIC");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303055200","Caixão pneumático - equipamento para trabalho em ambiente de pressão anormal");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303055400","Escafandro - equipamento para trabalho em ambiente de pressão anormal");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303055600","Equipamento de mergulho - equipamento para trabalho em ambiente de pressão anormal");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303055900","Equipamento para trabalho em ambiente de pressão anormal, NIC");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303060000","Forno, estufa, retorta, aquecedor de ambiente, fogão, etc., exceto quando a lesão principal for choque elétrico ou eletroplessão - equipamento de aquecimento");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303065000","Equipamento emissor de radiação não ionizante");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303065300","Equipamento de iluminação - equipamento emissor de radiação não ionizante");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303065600","Arco elétrico - equipamento emissor de radiação não ionizante");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303065900","Equipamento emissor de radiação não ionizante, NIC");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303066300","Equipamento de iluminação");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303066600","Arco elétrico");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303070200","Equipamento de raios X - equipamento ou substância emissores de radiação ionizante");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303070400","Reator (inclui combustível e resíduo) - equipamento ou substância emissores de radiação ionizante");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303070600","Fonte de radioisótopo - equipamento ou substância emissores de radiação ionizante");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303070900","Equipamento ou substância emissores de radiação ionizante, NIC");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303075100","Bicicleta");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303075150","Triciclo");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303075200","Motocicleta, motoneta");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303075250","Veículo rodoviário motorizado");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303075300","Veículo sobre trilho");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303075350","Veículo aquático");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303075400","Aeronave");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303075450","Empilhadeira");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303075500","Rebocador mecânico, mula mecânica");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303075550","Carro-de-mão");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303075600","Trator");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303075650","Veículo de terraplenagem");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303075700","Veículo de tração animal");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303075750","Veículo deslizante");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303075800","Veículo funicular (tração por cabo)");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303075900","Veículo, NIC");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("303090000","Ferramenta, máquina, equipamento, veículo, NIC");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305004100","Composto metálico (de chumbo, mercúrio, zinco, cadmio, cromo, etc.)");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305004150","Composto de arsênio");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305004200","Gás carbônico (dióxido de carbono, CO2)");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305004250","Monóxido de carbono (CO)");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305004300","Óxidos de Nitrogênio (vapores nitrosos)");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305004350","Ácido");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305004400","Álcali");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305004450","Composto de fósforo");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305004500","Dissulfeto de carbono");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305004550","Cianeto ou composto de cianogênio");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305004600","Álcool");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305004650","Tetracloreto de carbono");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305004700","Composto orgânico halogenado (tricloretileno, percloretileno, cloreto de metilo, substâncias refrigerantes)");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305004750","Composto aromático (benzol, toluol, xilol, anilina, etc.)");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305004900","Substância química, NIC");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305008500","Água - usar quando o estado líquido contribuir preponderantemente para a ocorrência");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305008900","Líquido, NIC");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305020000","Partículas - não identificadas");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305024100","Pele, crina, pelo, lã (em bruto) - produto animal");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305024300","Pena - produto animal");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305024500","Couro cru ou curtido - produto animal");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305024700","Osso - produto animal");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305024900","Produto animal, NIC");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305028000","Madeira (toro, madeira serrada, pranchão, poste, barrote, ripa e produto de madeira)");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305032000","Produto mineral metálico - produto de mineração em bruto ou beneficiado, como minério e concentrado de minério");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305032500","Metal - inclui liga ferrosa e não ferrosa, tubo, placa, perfil, trilho, vergalhão, arame, porca, rebite, prego, etc. inclui metal fundido, lingote e sucata de fundição, exceto minério");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305036000","Produto mineral não metálico - produto de mineração, escavação, desbarrancamento, etc., como detrito, argila, areia, cascalho, pedra, etc.");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305040100","Petróleo bruto, bruto reduzido");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305040150","Asfalto, alcatrão, piche");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305040200","Óleo combustível");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305040250","Parafina, óleo lubrificante e de corte, graxas");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305040300","Gasóleo, óleo diesel");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305040350","Querosene");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305040400","Nafta e solvente de nafta (éter de petróleo, álcool mineral, solvente aromático, etc.)");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305040450","Gasolina (exceto quando a ocorrência for causada preponderantemente por composto de chumbo)");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305040500","Hidrocarboneto gasoso (inclui gás liquefeito, gás encanado de nafta, gás natural)");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305040600","Carvão");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305040650","Coque");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305040700","Gás encanado de carvão");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305040900","Produto de petróleo e de carvão, NIC");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305044000","Vidraria, fibra de vidro, lâmina, etc., exceto frasco, garrafa");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305048000","Cerâmica");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305048300","Tijolo e telha - cerâmica");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305048400","Louça de mesa e outros utensílios (de porcelana, barro, etc.) - cerâmica");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305048500","Tubo, manilha - cerâmica");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305048600","Revestimento cerâmico (azulejo, mosaico, etc.) - cerâmica");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305048700","Louca sanitária (pia, vaso sanitário, etc.) - cerâmica");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305048900","Cerâmica, NIC");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305052000","Têxteis - inclui fibras animais após o primeiro desengorduramento e limpeza, fibras vegetais e sintéticas (exceto vidro), fio, linha, tecido, passamanaria, feltro e produtos têxteis em geral");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305056000","Plástico - inclui pó, folha, trefilado, barra, perfil, etc., não incluindo produto a ser usado no fabrico de plástico");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305060000","Papel e pasta para papel");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305064000","Produtos alimentícios inclui carne leite e derivados legumes frutas cerais e derivados");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305064300","Carne e derivados - inclusive de origem animal");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305064400","Leite e derivados - inclusive de origem animal");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305064500","Legume, verdura e derivados");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305064600","Fruta e derivados");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305064700","Cereal e derivados");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305064900","Produto alimentício - inclusive de origem animal, NIC");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305068300","Medicamento em geral (exceto produto biológico)");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305068600","Produto biológico (soro, toxina, antitoxina, vacina, plasma) - medicamento");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305072000","Produto de limpeza, sabão, detergente");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305076000","Sucata, entulho, resíduo");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("305090000","Substância química, material, produto, NIC");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("306020000","Animal vivo");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("306040000","Vegetal - planta, árvore, em estado natural, não beneficiada (não inclui grão debulhado, fruto colhido, toro mesmo com galho)");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("306060000","Agente infeccioso ou parasitário - inclui bactéria, fungo, organismo parasitário, vírus, etc., não incluindo produto químico, preparado farmacêutico ou alimento");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("306090000","Ser vivo, NIC");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("307030100","Cadeira banco - mobiliário e acessórios");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("307030200","Mesa, carteira, exceto mesa elástica desmontável - mobiliário e acessórios");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("307030250","Mesa elástica desmontável - mobiliário e acessórios");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("307030300","Balcão, bancada - mobiliário e acessórios");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("307030400","Arquivo, fichário, estante - mobiliário e acessórios");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("307030500","Tapete, forração de piso, capacho - mobiliário e acessórios");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("307030600","Luminária, globo, lâmpada - mobiliário e acessórios");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("307030900","Mobiliário e acessórios, NIC");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("307040100","Caixa, engradado, caixote - embalagem, recipiente, vazio ou cheio");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("307040300","Frasco, garrafa - embalagem, recipiente, vazio ou cheio");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("307040500","Barril, barrica, barrilete, tambor - embalagem, recipiente, vazio ou cheio");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("307040700","Tanque, cilindro (transportáveis e não sob pressão) - embalagem, recipiente, vazio ou cheio");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("307040900","Embalagem e recipiente, vazio ou cheio, NIC");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("307050900","Vestuário, NIC");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("307070000","Área ou ambiente de trabalho - o agente do acidente ocorrido em consequência de fenômeno atmosférico, meteoro, etc., assim como da ação da radiação solar, deverá ser incluído neste item");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("309000000","Agente do acidente, NIC");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("309500000","Agente do acidente inexistente");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("354000000","Energia");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("354010300","Pressão ambiente alta trabalho em caixão pneumático mergulho");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("354010600","Pressão ambiente baixa ar rarefeito");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("354020000","Ruído");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("354040000","Fogo chama material incandescente ou quente fumaça");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("354050300","Temperatura ambiente - não inclui a de objeto ou substância quente");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("355016000","Aerodispersóides");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("355016600","Neblina");
INSERT INTO AgentesCausadores (agenteCausadorId,agenteCausadorDescricao) VALUES("355016800","Gás e vapor");
