INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200004300",	"Impacto de pessoa contra objeto parado");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200004600",	"Impacto de pessoa contra objeto em movimento");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200008300",	"Impacto sofrido por pessoa de objeto que cai");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200008600",	"Impacto sofrido por pessoa de objeto projetado");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200008900",	"Impacto sofrido por pessoa, NIC");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200012200",	"Queda de pessoa com diferença de nível de andaime, passagem, plataforma, etc.");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200012300",	"Queda de pessoa com diferença de nível de escada móvel ou fixada cujos degraus");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200012400",	"Queda de pessoa com diferença de nível de material empilhado");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200012500",	"Queda de pessoa com diferença de nível de veículo");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200012600",	"Queda de pessoa com diferença de nível em escada permanente");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200012700",	"Queda de pessoa com diferença de nível em poço, escavação, abertura no piso, etc.");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200012900",	"Queda de pessoa com diferença de nível, NIC");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200016300",	"Queda de pessoa em mesmo nível em passagem ou superfície de sustentação");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200016600",	"Queda de pessoa em mesmo nível sobre ou contra alguma coisa");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200016900",	"Queda de pessoa em mesmo nível, NIC");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200020100",	"Aprisionamento em, sobre ou entre objetos em movimento convergente");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200020300",	"Aprisionamento em, sobre ou entre objeto parado e outro em movimento");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200020500",	"Aprisionamento em, sobre ou entre dois ou mais objetos em movimento");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200020700",	"Aprisionamento em, sobre ou entre desabamento ou desmoronamento");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200020900",	"Aprisionamento em, sob ou entre, NIC");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200024300",	"Atrito ou abrasão por encostar, pisar, ajoelhar ou sentar em objeto");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200024400",	"Atrito ou abrasão por manusear objeto");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200024500",	"Atrito ou abrasão por objeto em vibração");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200024600",	"Atrito ou abrasão por corpo estranho no olho");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200024700",	"Atrito ou abrasão por compressão repetitiva");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200024900",	"Atrito ou abrasão, NIC");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200028300",	"Reação do corpo a movimento involuntário");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200028600",	"Reação do corpo a movimento voluntário");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200032200",	"Esforço excessivo ao erguer objeto");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200032400",	"Esforço excessivo ao empurrar ou puxar objeto");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200032600",	"Esforço excessivo ao manejar, sacudir ou arremessar objeto");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200032900",	"Esforço excessivo, NIC");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200036000",	"Elétrica, exposição a energia");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200040300",	"Temperatura muito alta, contato com objeto ou substância a");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200040600",	"Temperatura muito baixa, contato com objeto ou substância a");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200044300",	"Temperatura ambiente elevada, exposição a");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200044600",	"Temperatura ambiente baixa, exposição a");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200048200",	"Inalação de substância cáustica, tóxica ou nociva");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200048400",	"Ingestão de substância cáustica");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200048600",	"Absorção de substância cáustica");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200048900",	"Inalação, ingestão ou absorção, NIC");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200052000",	"Imersão");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200056000",	"Radiação não ionizante, exposição a");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200060000",	"Radiação ionizante, exposição a");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200064000",	"Ruído, exposição a");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200068000",	"Vibração, exposição a");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200072000",	"Pressão ambiente, exposição a");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200072300",	"Exposição à pressão ambiente elevada");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200072600",	"Exposição à pressão ambiente baixa");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200076200",	"Poluição da água, ação da (exposição à poluição da água)");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200076400",	"Poluição do ar, ação da (exposição à poluição do ar)");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200076600",	"Poluição do solo, ação da (exposição à poluição do solo)");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200076900",	"Poluição, NIC, exposição a (exposição à poluição, NIC)");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200080200",	"Ataque de ser vivo por mordedura, picada, chifrada, coice, etc.");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200080400",	"Ataque de ser vivo com peçonha");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200080600",	"Ataque de ser vivo com transmissão de doença");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("200080900",	"Ataque de ser vivo, NIC");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("209000000",	"Tipo, NIC");
INSERT INTO CodigosNaturezaLesao (codigoNaturezaLesaoId,codigoNaturezaLesaoDescricao) VALUES ("209500000",	"Tipo inexistente");
